{{- if .Values.common.ns.enabled }}
{{- range $app := .Values.application -}}
{{- if $app.ing.public.enabled -}}
{{- range $idx, $_ := $app.ing.public.target -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.domainCode }}-{{ $app.name }}-pub-ing-{{ .order }}
  namespace: {{ include "ddd-helm.namespace" $ }}
  labels:
    {{- include "ddd-helm.commonLabels" $ | nindent 4 }}
    {{- include "ddd-helm.componentLabel" $app | nindent 4 }}
    {{- if $app.ing.public.labelsTemplate }}
    {{- tpl $app.ing.public.labelsTemplate $ | nindent 4 }}
    {{- end }}
    {{- if $app.ing.public.labels }}
    {{- toYaml $app.ing.public.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $app.ing.public.annotationsTemplate }}
    {{- tpl $app.ing.public.annotationsTemplate $ | nindent 4 }}
    {{- end }}
    {{- if $app.ing.public.annotations }}
    {{- toYaml $app.ing.public.annotations | nindent 4 }}
    {{- end }}
    alb.ingress.kubernetes.io/group.name: {{ $app.ing.public.name }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ $app.ing.public.name }}
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    {{- if $app.ing.public.listener.ports }}
    alb.ingress.kubernetes.io/listen-ports: {{ toJson $app.ing.public.listener.ports | quote }}
    {{- end }}
    {{- if $app.ing.public.listener.tls.enabled }}
    alb.ingress.kubernetes.io/certificate-arn: {{ $app.ing.public.listener.tls.certARN }}
    alb.ingress.kubernetes.io/ssl-policy: {{ $app.ing.public.listener.tls.policy }}
    {{- if $app.ing.public.listener.tls.redirectPort }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ $app.ing.public.listener.tls.redirectPort | quote }}
    {{- end }}
    {{- end }}
    {{- range $key, $value := $app.ing.public.actions }}
    alb.ingress.kubernetes.io/actions.{{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := $app.ing.public.conditions }}
    alb.ingress.kubernetes.io/conditions.{{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if $app.ing.public.attributes }}
    alb.ingress.kubernetes.io/load-balancer-attributes: {{ $app.ing.public.attributes }}
    {{- end }}
    {{- if $app.ing.public.ip.type }}
    alb.ingress.kubernetes.io/ip-address-type: {{ $app.ing.public.ip.type }}
    {{- end }}
    {{- if $app.ing.public.ip.ipv4Pool }}
    alb.ingress.kubernetes.io/customer-owned-ipv4-pool: {{ $app.ing.public.ip.ipv4Pool }}
    {{- end }}
    {{- if $app.ing.public.ip.subnets }}
    alb.ingress.kubernetes.io/subnets: {{ $app.ing.public.ip.subnets }}
    {{- end }}
    {{- if $app.ing.public.ip.sourceRanges }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ $app.ing.public.ip.sourceRanges }}
    {{- end }}
    {{- if $app.ing.public.ip.frontendSecurityGroups }}
    alb.ingress.kubernetes.io/security-groups: {{ $app.ing.public.ip.frontendSecurityGroups }}
    {{- end }}
    {{- if $app.ing.public.ip.backendSecurityGroupManaged }}
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: {{ $app.ing.public.ip.backendSecurityGroupManaged | quote }}
    {{- end }}
    {{- if $app.ing.public.tags }}
    alb.ingress.kubernetes.io/tags: {{ $app.ing.public.tags }}
    {{- end }}
    {{- if $app.ing.public.wafAclID }}
    alb.ingress.kubernetes.io/waf-acl-id: {{ $app.ing.public.wafAclID }}
    {{- end }}
    {{- if $app.ing.public.wafv2AclID  }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ $app.ing.public.wafv2AclID }}
    {{- end }}
    {{- if $app.ing.public.shieldAdvancedProtection }}
    alb.ingress.kubernetes.io/shield-advanced-protection: {{ $app.ing.public.shieldAdvancedProtection }}
    {{- end }}
    alb.ingress.kubernetes.io/group.order: {{ .order | quote }}
    {{- if .type }}
    alb.ingress.kubernetes.io/target-type: {{ .type }}
    {{- end }}
    {{- if and (eq .type "instance") .nodeLabels }}
    alb.ingress.kubernetes.io/target-node-labels: {{ .nodeLabels }}
    {{- end }}
    {{- if .protocol }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .protocol }}
    {{- end }}
    {{- if .protocolVersion }}
    alb.ingress.kubernetes.io/backend-protocol-version: {{ .protocolVersion }}
    {{- end }}
    {{- if .attributes }}
    alb.ingress.kubernetes.io/target-group-attributes: {{ .attributes }}
    {{- end }}
    {{- if .healthCheck.protocol }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .healthCheck.protocol }}
    {{- end }}
    {{- if .healthCheck.port }}
    alb.ingress.kubernetes.io/healthcheck-port: {{ .healthCheck.port | quote }}
    {{- end }}
    {{- if .healthCheck.path }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .healthCheck.path }}
    {{- end }}
    {{- if .healthCheck.interval }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: {{ .healthCheck.interval | quote }}
    {{- end }}
    {{- if .healthCheck.timeout }}
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: {{ .healthCheck.timeout | quote }}
    {{- end }}
    {{- if .healthCheck.successCode }}
    alb.ingress.kubernetes.io/success-codes: {{ .healthCheck.successCode | quote }}
    {{- end }}
    {{- if .healthCheck.healthyThreshold }}
    alb.ingress.kubernetes.io/healthy-threshold-count: {{ .healthCheck.healthyThreshold | quote }}
    {{- end }}
    {{- if .healthCheck.unhealthyThreshold }}
    alb.ingress.kubernetes.io/unhealthy-threshold-count: {{ .healthCheck.unhealthyThreshold | quote }}
    {{- end }}
spec:
  {{- if $app.ing.public.className }}
  ingressClassName: {{ $app.ing.public.className }}
  {{- end }}
  {{- if and (eq $idx 0) $app.ing.public.defaultRule.enabled }}
  defaultBackend:
    service:
      name: {{ $app.ing.public.defaultRule.svc.name }}
      port:
        name: {{ $app.ing.public.defaultRule.svc.portName }}
  {{- end }}
  rules:
    {{- range .rules }}
    - http:
        paths:
          {{- range .paths }}
          - pathType: {{ .type }}
            path: {{ .path | quote }}
            backend:
              service:
                name: {{ .svc.name }}
                port:
                  name: {{ .svc.portName }}
          {{- end }}
      {{- if .host }}
      host: {{ .host | quote }}
      {{- end }}
    {{- end }}
---
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}