{{- if .Values.common.ns.enabled }}
{{- range $app := .Values.application -}}
{{- if $app.pv.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.domainCode }}-{{ $app.name }}-static-pvc
  namespace: {{ include "ddd-helm.namespace" $ }}
  labels:
    {{- include "ddd-helm.commonLabels" $ | nindent 4 }}
    {{- include "ddd-helm.componentLabel" $app | nindent 4 }}
    {{- if $app.pv.labelsTemplate }}
    {{- tpl $app.pv.labelsTemplate $ | nindent 4 }}
    {{- end }}
    {{- if $app.pv.labels }}
    {{- toYaml $app.pv.labels | nindent 4 }}
    {{- end }}
  {{- if or $app.pv.annotationsTemplate $app.pv.annotations }}
  annotations:
    {{- if $app.pv.annotationsTemplate }}
    {{- tpl $app.pv.annotationsTemplate $ | nindent 4 }}
    {{- end }}
    {{- if $app.pv.annotations }}
    {{- toYaml $app.pv.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml $app.pv.accessMode | nindent 4 }}
  # selector:
  resources:
    requests:
      storage: {{ $app.pv.size }}
  volumeName: {{ $.Values.domainCode }}-{{ $app.name }}-static-pv
  storageClassName: ""
  volumeMode: {{ $app.pv.volumeMode }}
---
{{- end -}}
{{- end -}}
{{- end -}}